### ISSUE TITLE
Doesn't validate D-number correctly

### ISSUE THREAD

**Issue by jorgenblindheim** [mikaello/norwegian-national-id-validator#30]
I've tested several D-numbers, and it both returns that it isn't a D-number and that it's not valid.

**Comment by JeroenBos** [comment]
Yes mine for instance. 
I don't know how many Norwegian websites and webshops etc use this library, but I am rejected very often on websites due to my D-number being "invalid", even though it is.

**Comment by mikaello** [comment]
Hm, thanks for giving me a heads up. I will investigate this.

**Comment by mikaello** [comment]
I have gone trough the code several times now, and been checking the rules for how D number works. 

If a D number could be `d d m m y y i1 i2 i3 c1 c2`, then if `i1 i2 i3` is lower than 500 the person is born in before 1. January, if `i1 i2 i3` is higher than or equal to 500 the person is born at or after 1. January 2000. The last part was not implemented in the code, but the D number was supposed to has the same rules as the birth number.

E.g.
* `50101099943` => 6 years old (`i1 i2 i3` equal to 999)
* `60101010085` => 109 years old (`i1 i2 i3` equal to 100)

This should be fixed in the last commit.

Could you confirm that it is fixed? And if not, would it be possible that you gave me a fictive or non-sensitive example of a D number that is considered not valid?

**Comment by jorgenblindheim** [comment]
That was fast! I'm struggling to get this package to work when I install it directly from master. From what I can see, it looks like it's not compiling the typescript like with npm. Any suggestions to how to get around this?

**Comment by mikaello** [comment]
Fixed in [v3.0.0](https://github.com/mikaello/norwegian-national-id-validator/releases/tag/v3.0.0), also released to NPM.

Thanks for reporting the issue @jorgenblindheim and for your feedback @JeroenBos
