### ISSUE TITLE
The example uses invalid national ids. 

### ISSUE THREAD

**Issue by fatso83** [mikaello/norwegian-national-id-validator#6]
The examples seems wrong and I am not sure why you return an array, when there is only one possible value:
```
possibleAgesOfPersonWithIdNumber('03111590925')
// => [101, 1]
```
This is incorrect for two reasons:
1. The first three digits of the _personnummer_ (the last five digits) are called _individsifre_ and can be used to determine which century/decennium an individual is born. Therefore, unless you are 200 years old (biological threshold of about 125 years), there is just a single value that should be possible, hence using an Array is incorrect.
2. The _individsifre_ of `909` means the individual should be born between 1940 and 1999, which would not match either of the returned values.

[Reference](https://no.wikipedia.org/wiki/F%C3%B8dselsnummer)

**Comment by mikaello** [comment]
Hi, @fatso83 , thanks for your interest!

You seem to be right in the `fødselsnummer` in the example could not belong to two persons. To elaborate: _individsifre_ of `909` could belong to persons born in the 19th and the 20th century, to cite Skatteetaten (same data as you found on Wikipedia):
> The three digits comprising the individual number are allocated sequentially within the specific date of birth. Individual digits are allocated as follows:
> 
> 1. born 1854-1899: allocated from series 749-500
> 1. born 1900-1999: allocated from series 499-000
> 1. born 1940-1999: also allocated from series 999-900
> 1. born 2000-2039: allocated from series 999-500

If you look at item 3 and 4, you can see that both of them share the range 999-900. But this means that the age of 101 is impossible (since the person born in the 19th century must be born after 1940, and 1915 would not be possible), and hence is the example in README wrong, and also the code:

https://github.com/mikaello/norwegian-national-id-validator/blob/d03063ab125dd46dc46e25b944f741a27e8971b4/src/index.js#L75-L77

Then, the only way a _fødselsnummer_ could match two different birth years is when you assume that persons born before 1854 also got _individsiffer_ in range 749-500, and then theoretically could share _individsiffer_ with persons born in the 20th century. This is not a valid assumption, and is a mistake.

I will try to fix this. Otherwise are PRs always welcome :-)
